version: '3.7'

services:
  web:
    image: local/blizzcon-schedule:2019.2
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blizzcon.rule=Host(`blizzcon.marlamin.com`)"
      - "traefik.http.routers.blizzcon.entrypoints=web"
      - "traefik.http.routers.blizzcon-secured.rule=Host(`blizzcon.marlamin.com`)"
      - "traefik.http.routers.blizzcon-secured.entrypoints=websecure"
      - "traefik.http.routers.blizzcon-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.blizzcon.loadbalancer.server.port=80"
      - "traefik.http.middlewares.schedule-redirectregex.redirectregex.regex=^(.*com)/{0,1}(\\?.*){0,1}$$"
      - "traefik.http.middlewares.schedule-redirectregex.redirectregex.replacement=$${1}/schedule"
      - "traefik.http.routers.blizzcon.middlewares=schedule-redirectregex@docker,httpsredirect@docker"
      - "traefik.http.routers.blizzcon-secured.middlewares=schedule-redirectregex@docker"

networks:
  default:
    external:
      name: public